### ISSUE TITLE
Search by city does not work

### ISSUE THREAD

**Issue by Sinapse87** [Ornias1993/fetlife-aslsearch-reborn#69]
# Description

## Category
BUG, TODO or feature?
Search by city does not seem to work

## Detailed Bug Report
Searching in my city produces zero result. It might be due to case or missing info in the db. Could we have a full list of all existing cities in the db?
## Steps to Reproduce
Enter Melbourne - Victoria - Australia in the city search and nothing will come up

**Comment by Sinapse87** [comment]
Hi, thanks a lot for your detailed response. Could we then omit the city and search by area and country? That did not work either. Is there a way to wildcard/skip the city field?

**Comment by Sinapse87** [comment]
Would you please try, because It does not work for me. Would you try to search only "Victoria", "Australia" please

**Comment by pp-lucaal-sportsbet** [comment]
I tried from my phone and it did not work. There is only one textField for city, state, and Country when browsing for the phone. Would you know what exactly needs to be typed "Victoria, Australia"? Thanks a lot

**Comment by Sinapse87** [comment]
I tried all sort of combination both with the stand alone script and the grease monkey extension but I could not make it work. Could you please try again? Thanks

**Comment by Sinapse87** [comment]
I tried this one:
https://script.google.com/macros/s/AKfycbzUFY6t94AxfmbLtBpTUvkjUkAma_j-17rJPPURrkvG6ZR5SPc/exec

And "Victoria" "Australia" returns no results.

Also when I use the browser extension

**Comment by Sinapse87** [comment]
I am using tampermonkey 4.9

**Comment by Sinapse87** [comment]
Don't be me at me, it does not work with my browser/extension combination. I'll try another browser...

**Comment by Sinapse87** [comment]
Hi, so a basic search like this:

![image](https://user-images.githubusercontent.com/4057155/71891304-707a2880-319a-11ea-954e-0aa76ff94a71.png)

Will produce zero results for me.

I am on Mac catalina 10.15.2
Chrome 79
And tampermonkey 4.9 

Let me know if there is any other info you need from me, to help with triage

**Comment by Sinapse87** [comment]
How long did you wait? Until it finished
Did you switch tabs? Yes I did
What region and country did you enter? Victoria, Australia
Did you add any other search terms? I tried with and without, same blank result

**Comment by Sinapse87** [comment]
I found the issue:

Sexual orientation does not seem to be scraped anymore, so if you use it you are not going to get anything in the report.

**Comment by Sinapse87** [comment]
It was working before not sure how it broke. I have to think the info is
not being scraped nomore..

**Comment by Sinapse87** [comment]
Maybe just the name of the field;)
