### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Slofe** [Ornias1993/fetlife-aslsearch-reborn#75]
# Description

## Category
Feature

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.
2.
3.

I dunno if this is OK but I've used this script off and on for a while now and there's a couple of things I'd like to see in it.

It's always mentioned that this script scraping users causes members to be banned. I personally never experienced this. I certainly tripped fetlife's systems where they locked me out for a while but that was only for a few hours and that was on a different asl scraper script. With this script I always went slow with scraping and never had any problems.

Waiting for a database to fill with users is pretty useless to me as I'm probably the only person in my area to use this script, except maybe for one or two others. So I have a couple of suggestions:

1. Would it be possible to scrape users in a certain area and do it at a really slow rate so as to be undetected? For example I could set it going overnight and check it in the morning? That would be really useful.

2. Would it also be possible to only scrape the same users once or at least indicate a particular user has already been seen by you? Perhaps adding a check box next to each profile that remains after each scrape? In the same way streaming platforms leave a check next to films or episodes already watched. This would make it much more efficient and prevent opening profiles only to discover they haven't been active for 8 years!

I don't know if any of these are possible but I think they would be extremely useful :)

**Comment by Ornias1993** [comment]
https://github.com/Ornias1993/fetlife-aslsearch-reborn/wiki/FAQ#why-dont-i-get-any-results
